version: '3.0'

services: 
  importer:
    build: load-data
    depends_on:
      - database


  database:
    image: mysql:8.0.27
    environment:
      - MYSQL_PASSWORD=extremesafepassword
      - MYSQL_DATABASE=codecompetition
      - MYSQL_USER=codecompetitor
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql:ro

  dashboard:
    image: grafana/grafana:8.3.3
    ports:
      - 8087:3000
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      #- GF_AUTH_ANONYMOUS_ORG_NAME=CodeCompetition
      - GF_AUTH_BASIC_ENABLE=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      #- GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/
  